require('nvim-treesitter').setup({
  ensure_installed = {
    'lua',
    'vim',
    'vimdoc',
    'rust',
    'typescript',
    'javascript',
    'python',
    'go',
    'bash',
    'json',
    'yaml',
    'html',
    'css',
    'tsx',
    'tsx',
    'markdown',
    'markdown_inline',
  },
  sync_install = false,
  auto_install = true,
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  indent = {
    enable = true,
  },
})
